# LA ORIENTACION DE OBJETOS TRATA DE MODELAR UN OBJETO DE LA VIDA REAL
# Y TIENE ATTRIBUTES (CONSTANTES DE COSAS QUE TIENE EL OBJETO) Y METHODS (LAS COSAS QUE HACE EL OBJETO)
# CAMARERO - TIENE LOS ATTRIBUTES(SUJETAR_PLATO = TRUE Y MESAS = [1, 2, 3]) Y LOS METHODS (DEF TOMAR NOTA() Y DEF COBRAR())
# SI A PARTIR DE UN MODELO DE OBJETO, SE CREAN VARIOS, SE DEFINE UNA CLASE

